### ISSUE TITLE
编译错误

### ISSUE THREAD

**Issue by lichao252244354** [BFEMCC/Qt-widget-Fancy_UI#3]
你好，请问你使用的qt版本是多少，我使用qt 5.12.9编译会有Project ERROR: Unknown module(s) in QT: core5compat错误

**Comment by COLORREF** [comment]
我的版本是Qt6.2.4，Qt5有些代码要修改

**Comment by lichao252244354** [comment]
好的，我试试Qt6.24编译是否OK

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年12月13日 17:32 |
| 收件人 | BFEMCC/Qt-widget-Fancy_UI ***@***.***> |
| 抄送人 | lichao252244354 ***@***.***>,
Author ***@***.***> |
| 主题 | Re: [BFEMCC/Qt-widget-Fancy_UI] 编译错误 (Issue #3) |

我的版本是Qt6.2.4，Qt5有些代码要修改
