### ISSUE TITLE
BorderlessWindow中的mainarea.cpp文件

### ISSUE THREAD

**Issue by lijinlong-yevs** [BFEMCC/Qt-widget-Fancy_UI#7]
paintEvent中的判断条件不是python的and或者or 需要修改为&&和||否则编译会报错

**Comment by lijinlong-yevs** [comment]
![Uploading Snipaste_2024-04-27_15-02-59.png…]()

**Comment by COLORREF** [comment]
C++很早就已经支持and、or等运算符，可能是你的C++标准过低、编译器不支持或没有开启此功能，我本地编译是可以通过的，详细请查看这些文档：
- https://learn.microsoft.com/zh-cn/cpp/c-runtime-library/iso646-operators?view=msvc-170
- https://www.bookstack.cn/read/wangdoc-clang-tutorial/docs-lib-iso646.h.md
- https://blog.csdn.net/maray/article/details/41644235
- https://zh.wikipedia.org/wiki/C%E6%9B%BF%E4%BB%A3%E6%A0%87%E8%AE%B0

**Comment by lijinlong-yevs** [comment]
好的多谢了

**Comment by COLORREF** [comment]
C++很早就已经支持and、or等运算符，可能是你的C++标准过低、编译器不支持或没有开启此功能，我本地编译是可以通过的，详细请查看这些文档：
- https://learn.microsoft.com/zh-cn/cpp/cpp/logical-and-operator-amp-amp?view=msvc-170
- https://learn.microsoft.com/zh-cn/cpp/cpp/logical-or-operator-pipe-pipe?view=msvc-170
- https://blog.csdn.net/maray/article/details/41644235
- https://zh.wikipedia.org/wiki/C%E6%9B%BF%E4%BB%A3%E6%A0%87%E8%AE%B0
________________________________
发件人: lijinlong-yevs ***@***.***>
发送时间: 2024年4月27日 15:02
收件人: COLORREF/QWidget-FancyUI ***@***.***>
抄送: Subscribed ***@***.***>
主题: [COLORREF/QWidget-FancyUI] BorderlessWindow中的mainarea.cpp文件 (Issue #7)


paintEvent中的判断条件不是python的and或者or 需要修改为&&和||否则编译会报错

―
