### ISSUE TITLE
大佬,关于borderlesswindow的问题.

### ISSUE THREAD

**Issue by 860000023** [BFEMCC/Qt-widget-Fancy_UI#9]
我下载了你的borderlesswindow感觉比我网上找的代码更好.但是就是没有接口让我和.ui关联,所以我自己尝试着去修改.

我在mianares 新增了一个函数
`void MainArea::setCentralWidget(QWidget* centralWidget) {
    this->vertical_layout->addWidget(centralWidget);
}
`

然后在BorderlessWindow
同样的新增了一个
`void BorderlessWindow::setCentralWidget(QWidget* centralWidget) {
    main_area->setCentralWidget(centralWidget);
}`

并屏蔽类初始化的this->vertical_layout->addWidget(this->customer_area_widget);

然后这样调用
`BorderlessWindow *w1 = new BorderlessWindow();
//w1.show();
qtui* w = new qtui(w1);
w1->setCentralWidget(w);
w1->show();`

我的UI窗口可以正常嵌入到无边框窗口, 但是当我改变窗口大小时,标题和右上角的按钮会移动到其它位置.不知道这是什么原因,希望大佬能指点一下,QT新手.研究了一下午也没搞定.谢谢

**Comment by 860000023** [comment]
已解决

**Comment by COLORREF** [comment]
borderlesswindow重大更新，感兴趣可以看一下

**Comment by 860000023** [comment]
好的.感谢大佬.
